#include <iostream>
#include <algorithm>

/**
 * You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.

    Example 1:

    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.
    
    Example 2:

    Input: s = "", t = "y"
    Output: "y"
*/

char findTheDifference(std::string s, std::string t) {
    std::sort(s.begin(), s.end());
    std::sort(t.begin(), t.end());
    for(int i = 0; i < t.length(); i++) {
        if (t[i] != s[i]) return t[i];
    }

    return 'a';
}

int main() {
    std::cout << findTheDifference("dabcf", "bceadf");
    return EXIT_SUCCESS;
}